🔀 :: (#248) sign up class ui
Walkhub/walkhub_android pull request #249
Opened 2022-02-25 10:50 UTC by limsaehyun

## 개요

sign up class ui

## UI
<img src="https://media.discordapp.net/attachments/909622882546647091/946720621642018836/Screenshot_20220225-194824_Walkhub.jpg?width=297&height=610" width="150px"></img>
<img src="https://media.discordapp.net/attachments/909622882546647091/946720621423890473/Screenshot_20220225-194830_Walkhub.jpg?width=297&height=610" width="150px"></img>
<img src="https://media.discordapp.net/attachments/909622882546647091/946720621205782538/Screenshot_20220225-194857_Walkhub.jpg?width=297&height=610" width="150px"></img>
<img src="https://media.discordapp.net/attachments/909622882546647091/946720620958351410/Screenshot_20220225-194903_Walkhub.jpg?width=297&height=610" width="150px"></img>

2022-02-25 17:56 UTC, shw0471 requested changes
Edit text 디자인이 좀 다른거같네

2022-03-03 02:51 UTC, aahspringaa4 reviewed
👍

2022-03-04 00:16 UTC, JaewonKim04 reviewed
onBackPressed()함수를 상속해서 BackPress했을때 처리도 해주세요.

2022-03-04 02:19 UTC, limsaehyun commented
@JaewonKim04 반영헀습니다!

2022-03-04 08:15 UTC, JaewonKim04 approved these changes
수고했어요.

2022-03-06 23:38 UTC, shw0471 approved these changes

2022-03-06 23:38 UTC, merged