🔀 :: (#251) 알림설정 UI 작성
Walkhub/walkhub_android pull request #254
Opened 2022-02-26 02:13 UTC by Leesin0222

## 개요
> 알림설정 UI를 짠다

## 기타사항
- switchbutton는 라이브러리를 사용하였다.

## UI
![image](https://user-images.githubusercontent.com/90879448/155825035-66f6fe49-3b7d-46b3-a4af-d948280e7959.png)

2022-02-27 13:44 UTC, shw0471 requested changes
Switch들 다 ComposeView써서 compose로 만들어둔 ToggleSwitch 쓰는거로 하자
바꾸면서 Dependency 추가된거도 지워줘 이거만 지우면 conflict도 해결될듯

2022-02-27 13:46 UTC, shw0471 requested changes
TextView Gravity들 다 center로 맞춰줘

2022-02-27 13:48 UTC, shw0471 requested changes

2022-02-27 13:48 UTC, shw0471 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +                android:src="@drawable/ic_back"
이거도 전처럼 56*56사이즈로 바꾸고
아이콘은 ic_back_arrow.png로 하고
padding 16dp 추가해줘

2022-02-27 13:48 UTC, shw0471 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +            android:layout_marginEnd="16dp"
아이콘 수정하고 이 마진들은 다 지워도 될듯

2022-03-02 02:30 UTC, Leesin0222 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +                android:src="@drawable/ic_back"
수정했습니다!

2022-03-02 02:30 UTC, Leesin0222 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +            android:layout_marginEnd="16dp"
수정했습니다!

2022-03-02 02:30 UTC, Leesin0222 commented
**수정했습니다**

2022-03-02 02:31 UTC, Leesin0222 commented
> TextView Gravity들 다 center로 맞춰줘

수정했습니다!

2022-03-03 10:06 UTC, limsaehyun commented on presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/NoticeSettingActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_notice_setting)
Base를 상속 받았기 때문에 필요 없는 코드인 것 같아요

2022-03-03 13:12 UTC, Leesin0222 commented
> Switch들 다 ComposeView써서 compose로 만들어둔 ToggleSwitch 쓰는거로 하자 바꾸면서 Dependency 추가된거도 지워줘 이거만 지우면 conflict도 해결될듯

수정했습니다.

2022-03-08 00:09 UTC, shw0471 requested changes

2022-03-08 00:09 UTC, shw0471 commented on presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/NoticeSettingActivity.kt
> +    }
이거 중복되는 코드가 너무 많은데
``` kotlin
fun ComposeView.setToggleSwitch(
    onToggleOn: () -> Unit,
    onToggleOff: () -> Unit
) = this.apply {
    setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
    setContent {
        ToggleSwitch(
            onToggleOn = { onToggleOn() },
            onToggleOff = { onToggleOff() }
        )
    }
}
```
이런 확장함수를 만들어서
``` kotlin
binding.challengeEndSwt.setToggleSwitch(
            onToggleOn = {},
            onToggleOff = {}
        )
```
이런식으로 코드 줄이면 좋을거같아

2022-03-08 00:09 UTC, shw0471 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +            android:layout_marginTop="26dp"
이거 28dp로 바꿔줘

2022-03-08 00:10 UTC, shw0471 requested changes
그리고 ComposeView들 사이즈 가로 40dp 세로 52dp로 바꾼다음
``` kotlin
ToggleSwitch(
            Modifier.padding(vertical = 16.dp),
            onToggleOn = {},
            onToggleOff = {}
        )
```
이런식으로 padding 넣어주는게 좋을거같아

2022-03-08 00:13 UTC, shw0471 requested changes
`AndroidManifest.xml` 파일에 NoticeSettingActivity 추가해줘

2022-03-08 00:19 UTC, shw0471 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +            app:layout_constraintTop_toBottomOf="@+id/constraintLayout" />
이거 constraintStart가 설정 안돼있어서 marginStart도 적용 안됐어

2022-03-08 06:46 UTC, Leesin0222 commented on presentation/src/main/res/layout/activity_notice_setting.xml
> +            app:layout_constraintTop_toBottomOf="@+id/constraintLayout" />
수정했습니다

2022-03-10 08:17 UTC, shw0471 approved these changes
👍

2022-03-10 08:17 UTC, merged