🔀 :: (#303) 설정 뷰작동 업데이투
Walkhub/walkhub_android pull request #304
Opened 2022-03-03 03:11 UTC by Leesin0222

## 개요
>계정 정보  intent 추가

2022-03-03 10:19 UTC, aahspringaa4 commented
🙂

2022-03-04 00:27 UTC, JaewonKim04 requested changes, later dismissed
설정 버튼 아이콘 나오면 넣어주세요. 그리고 setting activity에 fragment가 없다는 오류와 supportedFragmentManager를 찾을 수 없다는 오류를 확인해주세요.

2022-03-04 00:27 UTC, JaewonKim04 commented on presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
> +import android.os.Bundle
필요없는 import문 지워주세요

2022-03-04 00:27 UTC, JaewonKim04 commented on presentation/src/main/res/layout/activity_setting.xml
> +        android:id="@+id/onfragment"
fragment가 아닌데 id가 fragment이면 안되요. id가 필요하다면 setting_cl로 바꿔주세요

2022-03-29 14:09 UTC, Leesin0222 commented
🐔

2022-03-29 14:20 UTC, limsaehyun approved these changes

2022-03-29 14:20 UTC, limsaehyun commented on presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
> +
안쓰는 부분은 TODO 사용해주세요

2022-03-30 00:26 UTC, merged