User Domain 구현 1
Walkhub/walkhub_android pull request #35
Opened 2022-01-20 03:36 UTC by limsaehyun

## 개요
> 
user쪽 기능이 많아 두 번으로 나눠서 진행합니다.

user의 Domain을 구현합니다.
 
## 작업사항

1. 전화번호 인증, 회원가입, 로그인, 비밀번호 변경, 유저 프로필 조회, 마이 페이지 조회 domain 구현
2. 전화번호 인증, 회원가입 data 구현 (실수..)

2022-01-20 06:53 UTC, aahspringaa4 commented
📑 :: user sign in entity 여기 커밋에서 expiredAt 형식 다시 확인해 주세요

2022-01-20 06:57 UTC, limsaehyun commented
@aahspringaa4 수정했습니다

2022-01-20 13:45 UTC, JaewonKim04 reviewed
`class`라고 이름 지어져있는 entity들은 classRoom이라고 해주세요. 그리고 풀리퀘 이름이 userDomain인데 data가 더 많아요.. 다음부터는 더 세분화 해서 풀리퀘 날리면 좋을것 같아요.

2022-01-20 13:45 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/remote/response/users/UserReissueResponse.kt
> +import java.time.LocalDateTime
필요없는 import는 지워주세요~

2022-01-20 13:45 UTC, JaewonKim04 commented on domain/src/main/java/com/semicolon/domain/entity/users/UserMypageEntity.kt
> +    val `class`: Int,
classRoom 이라고 이름 정해도 좋을것 같아요

2022-01-22 12:08 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/remote/response/users/UserReissueResponse.kt
> +import java.time.LocalDateTime
@JaewonKim04 수정했습니다!

2022-01-22 12:08 UTC, limsaehyun commented on domain/src/main/java/com/semicolon/domain/entity/users/UserMypageEntity.kt
> +    val `class`: Int,
@limsaehyun 수정했습니다!

2022-01-23 15:33 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
> +class UserRepositoryImpl @Inject constructor(
UserRepository 인터페이스에 있는 메소드가 모두 구현되지 않아있어요. 구현해주세요.

2022-01-23 15:33 UTC, JaewonKim04 commented on domain/src/main/java/com/semicolon/domain/entity/users/UserSignInEntity.kt
> +data class UserSignInEntity(
refreshtoken 이랑 accesstoken은 domain 영역에서 몰라도 됩니다. entity에 들어가있지 않아도 될것같아요.

2022-02-04 11:41 UTC, JaewonKim04 requested changes
앞에서 말한 inner클래스로 들어가있는 엔티티들을 @Entity로 따로 파서 만들어야할것같아. Entity두개를 합쳐서 쓰는 방법은  내가 ChallengeRoomEntity 랑 ChallengeDetailRoomEntity를 ChallengeAndDetail로 합쳐서 만든거 있으니깐 그거 참고하면 될거야. 다 만들고나서 Rebuild 눌러서 되는지 안되는지 확인해봐.

2022-02-04 11:41 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/entity/user/UserOwnBadgeRoomEntity.kt
> +    @SerializedName("badge_list") val badgeList: List<Badge>
Room에 저장할때는 List<Badge> 이런식으로 따로 만들어둔 클래스로 저장하면 안돼.

2022-02-04 11:41 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/entity/user/UserProfileRoomEntity.kt
> +    data class TitleBadge(
여기도 마찬가지로 Entityd안에 TitleBadge가 있으면 안돼. Inner 클래스로 들어가있는 TitleBadge 클래스를 따로 Entitiy로 만들어 줘야할것같아.

2022-02-04 11:41 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
> +    val titleBadge: TitleBadge,
TitleBadge가 안에 있으면 안돼.

2022-02-04 14:54 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
> +class UserRepositoryImpl @Inject constructor(
구현 완료 했습니다!

2022-02-04 14:54 UTC, limsaehyun commented on domain/src/main/java/com/semicolon/domain/entity/users/UserSignInEntity.kt
> +data class UserSignInEntity(
넵 반영했습니다.

2022-02-05 08:49 UTC, limsaehyun commented
List<Badge>가 저장이 안되는 현상은 badge list를 저장하는 converter를 생성하여 해결하였습니다.
그리고 중첩 클래스 TitleBadge는 @Embedded 를 앞에 붙여줌으로써 해결하였습니다.
리뷰 감사합니다 !!

2022-02-06 11:17 UTC, JaewonKim04 requested changes
아직도 빌드시에 오류가 많이 발생해요. 커밋하기전에 초록색 화살표나 혹은 Rebuild버튼 눌러서 꼭 빌드가 되는지 확인해주세요.

2022-02-06 11:17 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
> +        ChallengeRoomEntity::class,
ChallengeRoomEntity::class 가 2개가 되어버렸어요. 그리고 ChallengeDetailRoomEntity, ChallengeParticipantRoomEntity가 없어져서 오류가 발생해요

2022-02-06 11:19 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
> +            .doOnNeedRefresh { localUserDataSource.insertUserProfile(userId, it) }
매개변수에 문제가 있네요. insertUserProfile 의 매개변수에는 UserProfileEntity만 들어가는데, userId도 매개변수로 넣으셨네요

2022-02-06 12:21 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
> +            .doOnNeedRefresh { localUserDataSource.insertUserProfile(userId, it) }
반영 했습니다. 빌드 성공했습니다 감사합니다.

2022-02-06 12:52 UTC, JaewonKim04 approved these changes
수고하셨어요~~

2022-02-06 12:52 UTC, merged