🔀 :: (#41) school api, entity 작성
Walkhub/walkhub_android pull request #42
Opened 2022-01-24 00:41 UTC by minjun8946

## 개요
- school api, entity
## 작업사항
- search school api, entity 개발

2022-01-24 00:42 UTC, minjun8946 commented
저희 학교 로고 설정 필요한가요??

2022-01-26 11:38 UTC, shw0471 commented
학교 로고 설정은 안 해도 될거같은데

2022-01-26 11:39 UTC, shw0471 requested changes

2022-01-26 11:39 UTC, shw0471 commented on data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
> +
여기 한칸 띄워진거 지워주세요

2022-01-26 11:39 UTC, shw0471 commented on data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
> +
7번째 줄

2022-01-26 11:46 UTC, shw0471 approved these changes
👍

2022-01-26 11:46 UTC, merged