🔀 ::  (#31) Rank logic
Walkhub/walkhub_android pull request #64
Opened 2022-02-06 08:42 UTC by Leesin0222

## 개요
> Rank 로직 구현

## 작업사항
- interface, response, datasource, datasourceimpl, usecase, data repository, domain repository, entity

## 변경로직
- 바뀐 명세에따라 interface , response , datasource, datasourceImpl다시짯습니다. 

## 기타사항
 현명이가 제 깃크라켄 을 잘못만져서 제 데이터부분 파일들과 도메인들들이 다 날라가서 다시 했습니다.
현명이 혼내주세요

2022-02-06 10:59 UTC, shw0471 commented on domain/src/main/java/com/semicolon/domain/usecase/rank/FetchUserRankUseCase.kt
> +        rankRepository.fetchUserRank(data,data,data)
대체 이건 왜이렇게한거야

2022-02-06 11:02 UTC, shw0471 commented on data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
> +    data class MyRanking(
Ranking이랑 MyRanking이랑 완전 똑같은데 그냥 Ranking 하나만 쓰자

2022-02-06 11:03 UTC, shw0471 commented on domain/src/main/java/com/semicolon/domain/usecase/rank/FetchOurSchoolUserRankUseCase.kt
> +        rankRepository.fetchOurSchoolUserRank(data, data)
이거도이러네

2022-02-07 05:10 UTC, aahspringaa4 commented
용진아 정말 실망이다

2022-02-07 07:11 UTC, aahspringaa4 reviewed
👍

2022-02-07 07:11 UTC, aahspringaa4 commented on data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
> +
불필요한 띄워쓰기가 많네요 지워주세요

2022-02-08 06:33 UTC, limsaehyun commented on domain/src/main/java/com/semicolon/domain/param/rank/FetchUserRankParam.kt
> +    val agencyCode:String,
코드들 코드 정리 단축키 통해서 정리해주면 좋을 것 같아요.

2022-02-09 03:33 UTC, aahspringaa4 commented on data/src/main/java/com/semicolon/data/local/entity/rank/OurSchoolUserRankRoomEntity.kt
> +        val userId: Int,
Primary Key를 써도 될것 같아요

2022-02-09 03:33 UTC, aahspringaa4 commented on data/src/main/java/com/semicolon/data/local/entity/rank/SearchUserRoomEntity.kt
> +        val userId: Int,
여기도요

2022-02-09 03:34 UTC, aahspringaa4 commented on data/src/main/java/com/semicolon/data/local/entity/rank/UserRankRoomEntity.kt
> +        val userId: Int,
여기도 ㅎ

2022-02-11 12:33 UTC, limsaehyun commented
Rank 명세가 바뀌어서 response, request 업데이트 해야 할 것 같아요

2022-02-12 20:16 UTC, JaewonKim04 requested changes
컴파일 과정에서 문제가 되는 코드가 있어요(RankListTypeConverter)
이런 부분은 신경써서 고쳐주세요.

2022-02-12 20:16 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
> +    private val moshi: Moshi
moshi 에 대한 import가 안되어있어요. 확인해주세요.

2022-02-12 20:16 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/dao/RankDao.kt
> +    @Query("SELECT * FROM UserRank")
table 이름은 소문자로 시작해주세요. 예:(UserRank x -> userRank o)

2022-02-12 20:16 UTC, JaewonKim04 commented on data/src/main/java/com/semicolon/data/local/datasource/LocalRankDataSourceImpl.kt
> +
마지막 줄바꿈은 지워주면 좋겠어요.

2022-02-12 22:53 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
> +    private val moshi: Moshi
develop에 import 되있길래
이 feature에서 import를 쓰면 문제가 될까봐 생각했서 저렇게 했는데
 아니었네요 import추가하겠습니다!!

2022-02-13 08:43 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
> +            .remoteData { remoteRankDataSource.searchUser(searchUserParam.name,searchUserParam.scope.toString(),searchUserParam.moreDateType.toString(),searchUserParam.grade,searchUserParam.classNum)
param을 request로 바꿔서 넘겨주면 좋을 것 같아요

2022-02-13 08:43 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
> +            .remoteData { remoteRankDataSource.searchSchool(searchSchoolParam.name,searchSchoolParam.moreDateType.toString()).toEntity() }
여기도

2022-02-13 08:43 UTC, limsaehyun commented on data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
> +            .remoteData { remoteRankDataSource.fetchOurSchoolUserRank(fetchOurSchoolUserRankParam.scope.toString(), fetchOurSchoolUserRankParam.moreDateType.toString()).toEntity() }
여기도

2022-02-15 05:32 UTC, minjun8946 commented on data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
> +
이렇게 2칸 띄워저 있는 것들 싹다 1줄씩 지워주세요.

2022-02-16 05:12 UTC, minjun8946 approved these changes

2022-02-16 05:18 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
> +
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/local/converter/RankListTypeConverter.kt
> +    private val moshi: Moshi
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/local/dao/RankDao.kt
> +    @Query("SELECT * FROM UserRank")
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/local/datasource/LocalRankDataSourceImpl.kt
> +
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on domain/src/main/java/com/semicolon/domain/usecase/rank/FetchUserRankUseCase.kt
> +        rankRepository.fetchUserRank(data,data,data)
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on data/src/main/java/com/semicolon/data/remote/response/ranks/OurSchoolUserRankResponse.kt
> +    data class MyRanking(
수정했습니다

2022-02-16 05:18 UTC, Leesin0222 commented on domain/src/main/java/com/semicolon/domain/usecase/rank/FetchOurSchoolUserRankUseCase.kt
> +        rankRepository.fetchOurSchoolUserRank(data, data)
수정했습니다

2022-02-16 14:30 UTC, aahspringaa4 approved these changes

2022-02-16 14:30 UTC, merged